# Generated by Django 5.2.11 on 2026-02-18 04:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Date of publishing')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('blockquote', 5), ('embed', 6), ('document', 7), ('table', 8), ('raw_html', 9), ('text', 3), ('email', 10), ('url', 11), ('boolean', 12), ('integer', 13), ('float', 14), ('decimal', 15), ('date', 16), ('time', 17), ('datetime', 18), ('rich_text', 19), ('choice', 20), ('page', 21), ('static', 22), ('list', 24), ('stream', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('attribute_name', 4)]], {}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 8: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 9: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 10: ('wagtail.blocks.EmailBlock', (), {}), 11: ('wagtail.blocks.URLBlock', (), {}), 12: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 13: ('wagtail.blocks.IntegerBlock', (), {}), 14: ('wagtail.blocks.FloatBlock', (), {}), 15: ('wagtail.blocks.DecimalBlock', (), {}), 16: ('wagtail.blocks.DateBlock', (), {}), 17: ('wagtail.blocks.TimeBlock', (), {}), 18: ('wagtail.blocks.DateTimeBlock', (), {}), 19: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 21: ('wagtail.blocks.PageChooserBlock', (), {}), 22: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 23: ('wagtail.blocks.CharBlock', (), {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'List of items'}), 25: ('wagtail.blocks.StreamBlock', [[('text', 23), ('image', 2)]], {'label': 'Nested Stream'})}, null=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
