# Generated by Django 5.2.11 on 2026-02-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('issue', '0003_topic_issue_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issue.topic'),
        ),
    ]
