# Generated by Django 5.2.11 on 2026-02-26 16:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('blockquote', 7), ('embed', 8), ('document', 9), ('table', 10), ('raw_html', 11), ('text', 12), ('email', 13), ('url', 14), ('boolean', 15), ('integer', 16), ('float', 17), ('decimal', 18), ('date', 19), ('time', 20), ('datetime', 21), ('rich_text', 22), ('choice', 23), ('page', 24), ('static', 25), ('list', 27), ('stream', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption displayed below the image', 'label': 'Caption', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width - image fills the entire text column, no wrap'), ('left', 'Float left - image sits left, text flows around the right side'), ('right', 'Float right - image sits right, text flows around the left side')], 'help_text': 'Choose how the image sits relative to the surrounding text', 'label': 'Image placement'}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 1), ('attribute_name', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 10: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 11: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.EmailBlock', (), {}), 14: ('wagtail.blocks.URLBlock', (), {}), 15: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {}), 17: ('wagtail.blocks.FloatBlock', (), {}), 18: ('wagtail.blocks.DecimalBlock', (), {}), 19: ('wagtail.blocks.DateBlock', (), {}), 20: ('wagtail.blocks.TimeBlock', (), {}), 21: ('wagtail.blocks.DateTimeBlock', (), {}), 22: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 24: ('wagtail.blocks.PageChooserBlock', (), {}), 25: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 26: ('wagtail.blocks.CharBlock', (), {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'List of items'}), 28: ('wagtail.blocks.StreamBlock', [[('text', 26), ('image', 2)]], {'label': 'Nested Stream'})}, null=True),
        ),
    ]
