# Generated by Django 5.2.11 on 2026-02-20 04:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_aspect',
            field=models.CharField(choices=[('3x1', 'Wide banner  (3 : 1)'), ('2x1', 'Panoramic    (2 : 1)'), ('16x9', 'Widescreen   (16 : 9)'), ('4x3', 'Classic      (4 : 3)'), ('1x1', 'Square       (1 : 1)')], default='3x1', help_text='Controls how the cover image is cropped', max_length=10, verbose_name='Cover aspect ratio'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_caption',
            field=models.CharField(blank=True, help_text='Optional caption shown below the cover image', max_length=500, verbose_name='Cover image caption'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('blockquote', 7), ('embed', 8), ('document', 9), ('table', 10), ('raw_html', 11), ('text', 5), ('email', 12), ('url', 13), ('boolean', 14), ('integer', 15), ('float', 16), ('decimal', 17), ('date', 18), ('time', 19), ('datetime', 20), ('rich_text', 21), ('choice', 22), ('page', 23), ('static', 24), ('list', 26), ('stream', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption displayed below the image', 'label': 'Caption', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribute_name', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 10: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 11: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 12: ('wagtail.blocks.EmailBlock', (), {}), 13: ('wagtail.blocks.URLBlock', (), {}), 14: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {}), 16: ('wagtail.blocks.FloatBlock', (), {}), 17: ('wagtail.blocks.DecimalBlock', (), {}), 18: ('wagtail.blocks.DateBlock', (), {}), 19: ('wagtail.blocks.TimeBlock', (), {}), 20: ('wagtail.blocks.DateTimeBlock', (), {}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 23: ('wagtail.blocks.PageChooserBlock', (), {}), 24: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 25: ('wagtail.blocks.CharBlock', (), {}), 26: ('wagtail.blocks.ListBlock', (25,), {'label': 'List of items'}), 27: ('wagtail.blocks.StreamBlock', [[('text', 25), ('image', 2)]], {'label': 'Nested Stream'})}, null=True),
        ),
    ]
