# Generated by Django 5.2.14 on 2026-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_body_alter_article_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='sort_by',
            field=models.CharField(choices=[('latest', 'Latest First'), ('oldest', 'Oldest First'), ('most_read', 'Most Read (30-day views)')], default='latest', help_text='How to order issues on this page.', max_length=20),
        ),
    ]
