# Generated by Django 5.2.11 on 2026-02-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_cover_image_aspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image_aspect',
            field=models.CharField(choices=[('3x1', 'Thin strip - very wide and short (good for landscapes & skylines)'), ('2x1', 'Wide banner - wide and cinematic (works well for most photos)'), ('16x9', 'Widescreen - standard TV shape (great for screenshots & events)'), ('4x3', 'Classic photo - everyday camera shape (suits portraits & objects)'), ('1x1', 'Square - equal width and height (good for faces & close-ups)')], default='2x1', help_text='Choose how the cover photo is cropped at the top of the article. If part of the photo gets cut off, try a different shape - or open the image in the image library and set a focal point to control which part stays in frame.', max_length=10, verbose_name='Image shape'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_caption',
            field=models.CharField(blank=True, help_text="Short description or credit shown beneath the cover photo. e.g. 'Photo: Jane Smith / Reuters'", max_length=500, verbose_name='Photo caption / credit'),
        ),
    ]
