# Generated by Django 5.2.11 on 2026-03-06 07:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('colored_heading', 4), ('paragraph', 5), ('image', 9), ('blockquote', 11), ('embed', 12), ('document', 13), ('table', 14), ('raw_html', 15), ('text', 16), ('email', 17), ('url', 18), ('boolean', 19), ('integer', 20), ('float', 21), ('decimal', 22), ('date', 23), ('time', 24), ('datetime', 25), ('rich_text', 26), ('choice', 27), ('page', 28), ('static', 29), ('list', 30), ('stream', 31)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 3: ('articles.wagtail_widgets.ColorPickerBlock', (), {'default': '#000000', 'help_text': 'Pick a color for the heading text (e.g. #FF0000).', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('heading_level', 2), ('text_color', 3)]], {'label': 'Colored Heading'}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional caption displayed below the image', 'label': 'Caption', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width - image fills the entire text column, no wrap'), ('left', 'Float left - image sits left, text flows around the right side'), ('right', 'Float right - image sits right, text flows around the left side')], 'help_text': 'Choose how the image sits relative to the surrounding text', 'label': 'Image placement'}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('alignment', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribute_name', 10)]], {}), 12: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 15: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 16: ('wagtail.blocks.TextBlock', (), {}), 17: ('wagtail.blocks.EmailBlock', (), {}), 18: ('wagtail.blocks.URLBlock', (), {}), 19: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 20: ('wagtail.blocks.IntegerBlock', (), {}), 21: ('wagtail.blocks.FloatBlock', (), {}), 22: ('wagtail.blocks.DecimalBlock', (), {}), 23: ('wagtail.blocks.DateBlock', (), {}), 24: ('wagtail.blocks.TimeBlock', (), {}), 25: ('wagtail.blocks.DateTimeBlock', (), {}), 26: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 28: ('wagtail.blocks.PageChooserBlock', (), {}), 29: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 30: ('wagtail.blocks.ListBlock', (1,), {'label': 'List of items'}), 31: ('wagtail.blocks.StreamBlock', [[('text', 1), ('image', 6)]], {'label': 'Nested Stream'})}, null=True),
        ),
    ]
