# Generated by Django 5.2.11 on 2026-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_body_en_article_body_hi_article_body_ta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='opened_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='read_fully_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
