# Generated by Django 5.2.11 on 2026-02-20 04:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_body_alter_article_cover_image_aspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('blockquote', 8), ('embed', 9), ('document', 10), ('table', 11), ('raw_html', 12), ('text', 6), ('email', 13), ('url', 14), ('boolean', 15), ('integer', 16), ('float', 17), ('decimal', 18), ('date', 19), ('time', 20), ('datetime', 21), ('rich_text', 22), ('choice', 23), ('page', 24), ('static', 25), ('list', 27), ('stream', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption displayed below the image', 'label': 'Caption', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width - image fills the entire text column, no wrap'), ('left', 'Float left - image sits left, text flows around the right side'), ('right', 'Float right - image sits right, text flows around the left side')], 'help_text': 'Choose how the image sits relative to the surrounding text', 'label': 'Image placement'}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alignment', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('text', 6), ('attribute_name', 7)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 10: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 11: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 12: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 13: ('wagtail.blocks.EmailBlock', (), {}), 14: ('wagtail.blocks.URLBlock', (), {}), 15: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {}), 17: ('wagtail.blocks.FloatBlock', (), {}), 18: ('wagtail.blocks.DecimalBlock', (), {}), 19: ('wagtail.blocks.DateBlock', (), {}), 20: ('wagtail.blocks.TimeBlock', (), {}), 21: ('wagtail.blocks.DateTimeBlock', (), {}), 22: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 24: ('wagtail.blocks.PageChooserBlock', (), {}), 25: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 26: ('wagtail.blocks.CharBlock', (), {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'List of items'}), 28: ('wagtail.blocks.StreamBlock', [[('text', 26), ('image', 2)]], {'label': 'Nested Stream'})}, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_aspect',
            field=models.CharField(choices=[('3x1', 'Thin strip - very wide and short (good for landscapes & skylines)'), ('2x1', 'Wide banner - wide and cinematic (works well for most photos)'), ('16x9', 'Widescreen - standard TV shape (great for screenshots & events)'), ('4x3', 'Classic photo - everyday camera shape (suits portraits & objects)'), ('1x1', 'Square - equal width and height (good for faces & close-ups)')], default='2x1', help_text='Choose how the cover photo is cropped at the top of the article. If part of the photo gets cut off, try a different shape - or open the image in the image library and set a focal point to control which part stays in frame.', max_length=10, verbose_name='Image shape'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_caption',
            field=models.CharField(blank=True, help_text="Short description or credit shown beneath the cover photo. e.g. 'Photo: Jane Smith / Reuters'", max_length=500, verbose_name='Photo caption / credit'),
        ),
    ]
