# Generated by Django 5.2.11 on 2026-03-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_opened_count_article_read_fully_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='opened_count',
        ),
    ]
