# Generated by Django 5.2.11 on 2026-04-25 12:14

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('issue', '0001_initial'),
        ('literati', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='editorial_board',
            field=models.ForeignKey(blank=True, help_text='Select an editorial board group for this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='literati.editorialboard'),
        ),
        migrations.AddField(
            model_name='issue',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='issuearticlereprint',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_appearances', to='articles.article'),
        ),
        migrations.AddField(
            model_name='issuearticlereprint',
            name='issue',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprinted_articles', to='issue.issue'),
        ),
        migrations.AddField(
            model_name='issueindexpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='issue.issueindexpage'),
        ),
        migrations.AddField(
            model_name='issueindexpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='issueindexpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='issue.IssueIndexPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='issuetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='issue.issue'),
        ),
        migrations.AddField(
            model_name='issuetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='issue.IssueTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='issue',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issue.topic'),
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(blank=True, help_text='The volume this issue belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issue.volume'),
        ),
    ]
