# Generated by Django 5.2.11 on 2026-02-25 14:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
        ('literati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueeditorialboardrelationship',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_roles', to='literati.literati'),
        ),
        migrations.AddField(
            model_name='issueeditorialboardrelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_board_relationship', to='issue.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issue.topic'),
        ),
    ]
