# Generated by Django 5.2.14 on 2026-05-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Topics'},
        ),
    ]
