# Generated by Django 5.2.14 on 2026-05-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_topic_options'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pdf_file',
            field=models.ForeignKey(blank=True, help_text='Upload a PDF version of this issue for readers to download', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
