# Generated by Django 5.2.14 on 2026-05-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_issue_pdf_file'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='issue',
            name='PDF_file',
            field=models.ForeignKey(blank=True, help_text='ലക്കം അപ്\u200cലോഡ് ചെയ്യാം', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
