# Generated by Django 5.2.14 on 2026-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_remove_issue_pdf_file_issue_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueindexpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='issueindexpage',
            name='sort_by',
            field=models.CharField(choices=[('latest', 'Latest First'), ('oldest', 'Oldest First'), ('most_read', 'Most Read (30-day views)')], default='latest', help_text='How to order issues on this page.', max_length=20),
        ),
    ]
