# Generated by Django 5.2.11 on 2026-03-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issue_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Volume number (e.g. 1, 2, 3…)', unique=True)),
                ('year_start', models.PositiveIntegerField(help_text='Starting year of the volume (e.g. 2024)')),
                ('year_end', models.PositiveIntegerField(blank=True, help_text='Ending year if the volume spans multiple years. Leave blank for a single-year volume.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Volumes',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_number',
            field=models.PositiveIntegerField(blank=True, help_text='Issue number within the volume (e.g. 1, 2, 3…)', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(blank=True, help_text='The volume this issue belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issue.volume'),
        ),
    ]
