# Generated by Django 5.2.11 on 2026-03-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_volume_issue_issue_number_issue_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='title',
            field=models.CharField(blank=True, help_text="Optional display title for the volume (e.g. 'Special Edition')", max_length=255),
        ),
    ]
