# Generated by Django 5.2.11 on 2026-03-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_volume_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='title',
        ),
    ]
