# Generated by Django 5.2.11 on 2026-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_remove_volume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#000000', help_text='Choose a color for this topic (hex format, e.g., #FF0000)', max_length=7),
        ),
    ]
