# Generated by Django 5.2.11 on 2026-04-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_issueindexpagetag_issueindexpage_tags_issuetag_and_more'),
        ('literati', '0006_editorialboard_editorialboardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='editorial_board',
            field=models.ForeignKey(blank=True, help_text='Select an editorial board group for this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='literati.editorialboard'),
        ),
    ]
