# Generated by Django 5.2.11 on 2026-04-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_issue_editorial_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueEditorialBoardRelationship',
        ),
    ]
