# Generated by Django 5.2.11 on 2026-04-21 04:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_delete_issueeditorialboardrelationship'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='audio_embed_url',
            field=models.URLField(blank=True, help_text='Paste an embed link for audio (e.g., SoundCloud, Spotify)', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='editorial',
            field=wagtail.fields.StreamField([('audio', 3), ('heading', 4), ('paragraph', 5), ('image', 9), ('blockquote', 11), ('embed', 12), ('document', 13), ('table', 14), ('raw_html', 15), ('text', 16), ('email', 17), ('url', 18), ('boolean', 19), ('integer', 20), ('float', 21), ('decimal', 22), ('date', 23), ('time', 24), ('datetime', 25), ('rich_text', 26), ('choice', 27), ('page', 28), ('static', 29), ('list', 31), ('stream', 32)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload an audio file (mp3, wav, etc.)', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Or paste an embed link (SoundCloud, etc.)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the audio', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('audio_file', 0), ('audio_embed_url', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'full title'}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional caption displayed below the image', 'label': 'Caption', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width - image fills the entire text column, no wrap'), ('left', 'Float left - image sits left, text flows around the right side'), ('right', 'Float right - image sits right, text flows around the left side')], 'help_text': 'Choose how the image sits relative to the surrounding text', 'label': 'Image placement'}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('alignment', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribute_name', 10)]], {}), 12: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 15: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 16: ('wagtail.blocks.TextBlock', (), {}), 17: ('wagtail.blocks.EmailBlock', (), {}), 18: ('wagtail.blocks.URLBlock', (), {}), 19: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 20: ('wagtail.blocks.IntegerBlock', (), {}), 21: ('wagtail.blocks.FloatBlock', (), {}), 22: ('wagtail.blocks.DecimalBlock', (), {}), 23: ('wagtail.blocks.DateBlock', (), {}), 24: ('wagtail.blocks.TimeBlock', (), {}), 25: ('wagtail.blocks.DateTimeBlock', (), {}), 26: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 28: ('wagtail.blocks.PageChooserBlock', (), {}), 29: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 30: ('wagtail.blocks.CharBlock', (), {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'List of items'}), 32: ('wagtail.blocks.StreamBlock', [[('text', 30), ('image', 6)]], {'label': 'Nested Stream'})}, null=True),
        ),
    ]
