# Generated by Django 5.2.11 on 2026-04-21 05:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_issue_audio_embed_url_issue_audio_file_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='Paste an embed link for video (e.g., YouTube, Vimeo)', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='editorial',
            field=wagtail.fields.StreamField([('audio', 3), ('video', 7), ('heading', 8), ('paragraph', 9), ('image', 13), ('blockquote', 15), ('embed', 16), ('document', 17), ('table', 18), ('raw_html', 19), ('text', 20), ('email', 21), ('url', 22), ('boolean', 23), ('integer', 24), ('float', 25), ('decimal', 26), ('date', 27), ('time', 28), ('datetime', 29), ('rich_text', 30), ('choice', 31), ('page', 32), ('static', 33), ('list', 35), ('stream', 36)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload an audio file (mp3, wav, etc.)', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Or paste an embed link (SoundCloud, etc.)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the audio', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('audio_file', 0), ('audio_embed_url', 1), ('caption', 2)]], {}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a video file (mp4, webm, etc.)', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Or paste an embed link (YouTube, Vimeo, etc.)', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the video', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('video_file', 4), ('video_embed_url', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'full title'}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional caption displayed below the image', 'label': 'Caption', 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width - image fills the entire text column, no wrap'), ('left', 'Float left - image sits left, text flows around the right side'), ('right', 'Float right - image sits right, text flows around the left side')], 'help_text': 'Choose how the image sits relative to the surrounding text', 'label': 'Image placement'}), 13: ('wagtail.blocks.StructBlock', [[('image', 10), ('caption', 11), ('alignment', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'The person to attribute the quote to', 'label': 'e.g. Mary Berry', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('text', 9), ('attribute_name', 14)]], {}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed (e.g. YouTube, Vimeo, SoundCloud)'}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 18: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 19: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Use with caution: raw HTML is not sanitised'}), 20: ('wagtail.blocks.TextBlock', (), {}), 21: ('wagtail.blocks.EmailBlock', (), {}), 22: ('wagtail.blocks.URLBlock', (), {}), 23: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 24: ('wagtail.blocks.IntegerBlock', (), {}), 25: ('wagtail.blocks.FloatBlock', (), {}), 26: ('wagtail.blocks.DecimalBlock', (), {}), 27: ('wagtail.blocks.DateBlock', (), {}), 28: ('wagtail.blocks.TimeBlock', (), {}), 29: ('wagtail.blocks.DateTimeBlock', (), {}), 30: ('wagtail.blocks.RichTextBlock', (), {'label': 'Rich Text (Full)'}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre'), ('right', 'Right')], 'help_text': 'Alignment choice'}), 32: ('wagtail.blocks.PageChooserBlock', (), {}), 33: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a placeholder block — content is defined in the template.', 'label': 'Divider / Separator'}), 34: ('wagtail.blocks.CharBlock', (), {}), 35: ('wagtail.blocks.ListBlock', (34,), {'label': 'List of items'}), 36: ('wagtail.blocks.StreamBlock', [[('text', 34), ('image', 10)]], {'label': 'Nested Stream'})}, null=True),
        ),
    ]
