# Generated by Django 5.2.11 on 2026-04-25 12:14

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(blank=True, max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('other', 'Other')], default='card', max_length=20)),
                ('payment_method_other', models.CharField(blank=True, max_length=100, verbose_name='Other Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='ReaderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('bio', models.TextField(blank=True, help_text='A short description about yourself.', max_length=500)),
                ('can_comment', models.BooleanField(default=True, help_text='Uncheck this to restrict this user from posting comments.')),
                ('gender', models.CharField(blank=True, choices=[('പുരുഷന്\u200d', 'Male'), ('സ്ത്രീ', 'Female'), ('നോണ്\u200d ബൈനറി / ക്വീര്\u200d', 'Non-binary / Queer'), ('പറയാന്\u200d താല്\u200dപര്യമില്ല', 'Prefer not to say'), ('മറ്റൊന്ന്', 'Other')], max_length=100)),
                ('gender_other', models.CharField(blank=True, max_length=100, verbose_name='Other Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, help_text='House / flat number, street name.', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Landmark, area, locality.', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_office', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, help_text='6-digit Indian pincode.', max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit Indian pincode.', regex='^[1-9][0-9]{5}$')])),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, choices=[('', '— Select State —'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('care_of_name', models.CharField(blank=True, max_length=255)),
                ('care_of_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='C/O Phone Number')),
                ('care_of_district', models.CharField(blank=True, max_length=100)),
                ('care_of_meghala', models.CharField(blank=True, max_length=100)),
                ('care_of_unit', models.CharField(blank=True, max_length=100)),
                ('subscription_plan', models.CharField(choices=[('none', 'No Subscription'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='none', help_text='Active subscription plan.', max_length=20)),
                ('subscription_start', models.DateTimeField(blank=True, help_text='When the current subscription period began.', null=True)),
                ('subscription_end', models.DateTimeField(blank=True, help_text='When the current subscription period expires.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('payment_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_user', to='reader.paymentdetails')),
            ],
            options={
                'verbose_name': 'Reader User',
                'verbose_name_plural': 'Reader Users',
            },
            bases=(models.Model, modelsearch.index.Indexed),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
