# Generated by Django 5.2.11 on 2026-03-01 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_alter_article_body'),
        ('issue', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(blank=True, help_text='Payment gateway used, e.g. "cashfree", "billdesk".', max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID returned by the payment gateway.', max_length=255)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Order ID sent to the payment gateway.', max_length=255)),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('other', 'Other')], default='card', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('subscription_plan', models.CharField(choices=[('none', 'No Subscription'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], default='none', help_text='Active subscription plan.', max_length=20)),
                ('subscription_start', models.DateTimeField(blank=True, help_text='When the current subscription period began.', null=True)),
                ('subscription_end', models.DateTimeField(blank=True, help_text='When the current subscription period expires.', null=True)),
                ('interested_topics', models.ManyToManyField(blank=True, help_text='Topics this reader is interested in.', related_name='interested_readers', to='issue.topic')),
                ('payment_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader', to='reader.paymentdetails')),
                ('read_articles', models.ManyToManyField(blank=True, help_text='Articles this reader has accessed.', related_name='readers', to='articles.article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
            },
        ),
    ]
