# Generated by Django 5.2.11 on 2026-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
