# Generated by Django 5.2.11 on 2026-04-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('issue', '0002_initial'),
        ('reader', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='readeruser',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, help_text='Articles this reader has bookmarked.', related_name='favorited_by', to='articles.article'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='favorite_issues',
            field=models.ManyToManyField(blank=True, help_text='Issues this reader has bookmarked.', related_name='favorited_by', to='issue.issue'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='interested_topics',
            field=models.ManyToManyField(blank=True, help_text='Topics this reader is interested in.', related_name='interested_readers', to='issue.topic'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='Visible next to your comments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='read_articles',
            field=models.ManyToManyField(blank=True, help_text='Articles this reader has accessed.', related_name='readers', to='articles.article'),
        ),
    ]
