# Generated by Django 5.2.11 on 2026-04-20 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_paymentdetails_gateway_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='House / flat number, street name.', max_length=255),
        ),
        migrations.AddField(
            model_name='reader',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Landmark, area, locality.', max_length=255),
        ),
        migrations.AddField(
            model_name='reader',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='pincode',
            field=models.CharField(blank=True, help_text='6-digit Indian pincode.', max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit Indian pincode.', regex='^[1-9][0-9]{5}$')]),
        ),
        migrations.AddField(
            model_name='reader',
            name='state',
            field=models.CharField(blank=True, choices=[('', '— Select State —'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50),
        ),
    ]
