# Generated by Django 5.2.11 on 2026-04-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_readeruser_favorite_articles_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='readeruser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique key to prevent duplicate payment processing.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of explicit consent to the Privacy Policy.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of agreement to Terms of Service for legal enforceability.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Marked when a user requests deletion; triggers the statutory data retention clock.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text="Special instructions for the courier (e.g., 'Leave at gate')."),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='is_print_subscriber',
            field=models.BooleanField(default=False, help_text='Designates whether this user receives the physical print magazine.'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Account status based on successful verification of primary contact method.'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Monitored for security auditing and to detect unauthorized account access.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, help_text="User's choice to receive non-essential marketing communications."),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='newsletter_opt_in_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the newsletter consent status last changed.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='print_delivery_status',
            field=models.CharField(choices=[('active', 'Active Delivery'), ('paused', 'Paused'), ('returned', 'Address Issue / Returned'), ('inactive', 'No Print Copy')], default='inactive', help_text='Current logistical status of the print delivery.', max_length=20),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='print_expiry_date',
            field=models.DateField(blank=True, help_text='When the print subscription ends (may differ from digital expiry).', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='privacy_version',
            field=models.CharField(blank=True, help_text='Specific version of Privacy Policy consented to (Required for Consent Versioning).', max_length=20),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Captured at signup to detect and prevent fraudulent bot registrations.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Specific version of Terms of Service agreed to by the user.', max_length=20),
        ),
    ]
