# Generated by Django 5.2.11 on 2026-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articleindexpagetag_articleindexpage_tags_articletag_and_more'),
        ('issue', '0012_delete_issueeditorialboardrelationship'),
        ('reader', '0003_reader_address_line_1_reader_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, help_text='Articles this reader has bookmarked.', related_name='favorited_by', to='articles.article'),
        ),
        migrations.AddField(
            model_name='reader',
            name='favorite_issues',
            field=models.ManyToManyField(blank=True, help_text='Issues this reader has bookmarked.', related_name='favorited_by', to='issue.issue'),
        ),
    ]
