# Generated by Django 5.2.14 on 2026-05-26 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_readeruser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readeruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='readeruser',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Flag indicating if this account has been anonymized under DPDPA/GDPR rules.'),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Flag indicating if the active subscription has been cancelled but remains in grace period.'),
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('none', 'No Subscription'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], help_text='Subscription plan type.', max_length=20)),
                ('subscription_start', models.DateTimeField(help_text='When this subscription period began.')),
                ('subscription_end', models.DateTimeField(help_text='When this subscription period expires/expired.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating if this is currently the active subscription record.')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Flag indicating if this subscription was cancelled prematurely.')),
                ('payment_details', models.ForeignKey(blank=True, help_text='Payment transaction details associated with this subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_records', to='reader.paymentdetails')),
                ('reader', models.ForeignKey(blank=True, help_text='The reader associated with this subscription record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reader User',
                'verbose_name_plural': 'Reader Users',
            },
        ),
    ]
