# Generated by Django 5.2.14 on 2026-05-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_readeruser_options_readeruser_is_anonymized_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readeruser',
            options={'verbose_name': 'Reader User', 'verbose_name_plural': 'Reader Users'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionhistory',
            options={'ordering': ['-subscription_start'], 'verbose_name': 'Subscription History', 'verbose_name_plural': 'Subscription Histories'},
        ),
    ]
