# Generated by Django 5.2.11 on 2026-04-24 04:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_reader_favorite_articles_reader_favorite_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_method_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Payment Method'),
        ),
        migrations.AddField(
            model_name='reader',
            name='care_of_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='care_of_meghala',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='care_of_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reader',
            name='care_of_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='C/O Phone Number'),
        ),
        migrations.AddField(
            model_name='reader',
            name='care_of_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='gender',
            field=models.CharField(blank=True, choices=[('പുരുഷന്\u200d', 'Male'), ('സ്ത്രീ', 'Female'), ('നോണ്\u200d ബൈനറി / ക്വീര്\u200d', 'Non-binary / Queer'), ('പറയാന്\u200d താല്\u200dപര്യമില്ല', 'Prefer not to say'), ('മറ്റൊന്ന്', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Gender'),
        ),
        migrations.AddField(
            model_name='reader',
            name='post_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
