# Generated by Django 5.2.14 on 2026-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_alter_readeruser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readeruser',
            name='age_declaration_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the 18+ age self-declaration at signup.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='dob_consent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of explicit consent to share date of birth.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='gender_consent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of explicit consent to share gender information.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='is_above_18',
            field=models.BooleanField(default=False, help_text='Self-declaration that the user is 18 years or older, captured at signup for DPDP compliance.'),
        ),
    ]
