# Generated by Django 5.2.14 on 2026-06-03 02:52

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_migrate_to_cryptographic_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readeruser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='readeruser',
            name='dob_consent_at',
        ),
        migrations.AddField(
            model_name='readeruser',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of birth only. Sufficient for demographic analytics; safer than full DOB.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='birth_year_consent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of explicit consent to share birth year for demographic analytics.', null=True),
        ),
        migrations.AddField(
            model_name='readeruser',
            name='read_history_consent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of explicit consent to track reading history. Cleared on revocation.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='phone_number_encrypted',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Fernet-encrypted phone number. Unreadable in raw DB dumps.', max_length=255, verbose_name='Phone Number (Encrypted)'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='phone_number_hash',
            field=models.CharField(help_text='HMAC-SHA256 of the phone number. Used for fast, secure exact-match lookups.', max_length=64, unique=True, verbose_name='Phone Number (Hash)'),
        ),
    ]
