# Generated by Django 5.2.14 on 2026-07-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_alter_readeruser_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readeruser',
            name='subscription_plan',
            field=models.CharField(choices=[('none', 'No Subscription'), ('complimentary', 'Complimentary (Temporary Access)'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('3_years', '3 Years'), ('5_years', '5 Years')], default='none', help_text='Active subscription plan.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription_plan',
            field=models.CharField(choices=[('none', 'No Subscription'), ('complimentary', 'Complimentary (Temporary Access)'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('3_years', '3 Years'), ('5_years', '5 Years')], help_text='Subscription plan type.', max_length=20),
        ),
    ]
