# Generated by Django 5.2.14 on 2026-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_alter_readeruser_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readeruser',
            name='staff_granted_by_board',
            field=models.BooleanField(default=False, help_text='True when is_staff was granted automatically because this user sits on the current editorial board (see literati.sync_editorial_staff). Revocation on leaving the board only touches users with this flag — manually appointed staff and superusers are never demoted.'),
        ),
    ]
