# Generated by Django 5.2.14 on 2026-07-18 07:53

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_body_alter_article_body_en_and_more'),
        ('issue', '0008_alter_issue_editorial'),
        ('reader', '0011_readeruser_staff_granted_by_board'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'പേയ്\u200cമെന്റ് വിവരങ്ങൾ', 'verbose_name_plural': 'പേയ്\u200cമെന്റ് വിവരങ്ങൾ'},
        ),
        migrations.AlterModelOptions(
            name='readeruser',
            options={'verbose_name': 'വായനക്കാരൻ', 'verbose_name_plural': 'വായനക്കാർ'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionhistory',
            options={'ordering': ['-subscription_start'], 'verbose_name': 'വരിസംഖ്യ ചരിത്രം', 'verbose_name_plural': 'വരിസംഖ്യ ചരിത്രങ്ങൾ'},
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='ഒരേ പേയ്\u200cമെന്റ് ഇരട്ടിക്കുന്നത് തടയാനുള്ള അദ്വിതീയ കീ.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_method',
            field=models.CharField(choices=[('card', 'ക്രെഡിറ്റ് / ഡെബിറ്റ് കാർഡ്'), ('upi', 'UPI'), ('netbanking', 'നെറ്റ് ബാങ്കിംഗ്'), ('wallet', 'വാലറ്റ്'), ('other', 'മറ്റുള്ളവ')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_method_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='മറ്റ് പേയ്\u200cമെന്റ് രീതി'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'തീർപ്പാക്കാത്തത്'), ('completed', 'പൂർത്തിയായി'), ('failed', 'പരാജയപ്പെട്ടു'), ('refunded', 'തിരികെ നൽകി')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, help_text='സ്വകാര്യതാ നയത്തിന് വ്യക്തമായ സമ്മതം നൽകിയ സമയമുദ്ര.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text='നിയമപരമായ സാധുതയ്ക്കായി സേവന വ്യവസ്ഥകൾ അംഗീകരിച്ച സമയമുദ്ര.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='വീട്/ഫ്ലാറ്റ് നമ്പർ, തെരുവിന്റെ പേര്.', max_length=255),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='ലാൻഡ്മാർക്ക്, പ്രദേശം, സ്ഥലം.', max_length=255),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='age_declaration_at',
            field=models.DateTimeField(blank=True, help_text='സൈൻഅപ്പിലെ 18+ പ്രായ സ്വയം-പ്രഖ്യാപനത്തിന്റെ സമയമുദ്ര.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='bio',
            field=models.TextField(blank=True, help_text='നിങ്ങളെക്കുറിച്ചുള്ള ഒരു ചെറു വിവരണം.', max_length=500),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ജനന വർഷം മാത്രം. ജനസംഖ്യാ വിശകലനത്തിന് മതിയാകും; പൂർണ്ണ ജനനത്തീയതിയെക്കാൾ സുരക്ഷിതം.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='birth_year_consent_at',
            field=models.DateTimeField(blank=True, help_text='ജനസംഖ്യാ വിശകലനത്തിനായി ജനന വർഷം പങ്കിടാൻ സമ്മതം നൽകിയ സമയമുദ്ര.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='can_comment',
            field=models.BooleanField(default=True, help_text='ഈ ഉപയോക്താവിനെ അഭിപ്രായങ്ങൾ പോസ്റ്റ് ചെയ്യുന്നതിൽ നിന്ന് തടയാൻ ഇത് അൺചെക്ക് ചെയ്യുക.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='care_of_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='C/O ഫോൺ നമ്പർ'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='ഉപയോക്താവ് ഇല്ലാതാക്കൽ അഭ്യർത്ഥിക്കുമ്പോൾ രേഖപ്പെടുത്തുന്നു; നിയമപരമായ ഡാറ്റ സൂക്ഷിപ്പ് കാലയളവ് ആരംഭിക്കുന്നു.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text="കൊറിയറിനുള്ള പ്രത്യേക നിർദ്ദേശങ്ങൾ (ഉദാ: 'ഗേറ്റിൽ ഏൽപ്പിക്കുക')."),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, help_text='ഈ വായനക്കാരൻ പ്രിയപ്പെട്ടതായി അടയാളപ്പെടുത്തിയ ലേഖനങ്ങൾ.', related_name='favorited_by', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='favorite_issues',
            field=models.ManyToManyField(blank=True, help_text='ഈ വായനക്കാരൻ പ്രിയപ്പെട്ടതായി അടയാളപ്പെടുത്തിയ ലക്കങ്ങൾ.', related_name='favorited_by', to='issue.issue'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='gender',
            field=models.CharField(blank=True, choices=[('പുരുഷന്\u200d', 'പുരുഷന്\u200d'), ('സ്ത്രീ', 'സ്ത്രീ'), ('നോണ്\u200d ബൈനറി / ക്വീര്\u200d', 'നോണ്\u200d ബൈനറി / ക്വീര്\u200d'), ('പറയാന്\u200d താല്\u200dപര്യമില്ല', 'പറയാന്\u200d താല്\u200dപര്യമില്ല'), ('മറ്റൊന്ന്', 'മറ്റൊന്ന്')], max_length=100),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='gender_consent_at',
            field=models.DateTimeField(blank=True, help_text='ലിംഗ വിവരം പങ്കിടാൻ സമ്മതം നൽകിയ സമയമുദ്ര.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='മറ്റ് ലിംഗം'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='interested_topics',
            field=models.ManyToManyField(blank=True, help_text='ഈ വായനക്കാരന് താൽപ്പര്യമുള്ള വിഷയങ്ങൾ.', related_name='interested_readers', to='issue.topic'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='is_above_18',
            field=models.BooleanField(default=False, help_text='DPDP അനുസരണത്തിനായി സൈൻഅപ്പ് സമയത്ത് രേഖപ്പെടുത്തിയ 18+ പ്രായ സ്വയം-പ്രഖ്യാപനം.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='DPDPA/GDPR ചട്ടപ്രകാരം ഈ അക്കൗണ്ട് അജ്ഞാതവൽക്കരിച്ചിട്ടുണ്ടോ എന്ന ഫ്ലാഗ്.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='സജീവ വരിസംഖ്യ റദ്ദാക്കിയെങ്കിലും ഗ്രേസ് കാലയളവിൽ തുടരുന്നു എന്ന ഫ്ലാഗ്.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='is_print_subscriber',
            field=models.BooleanField(default=False, help_text='ഈ ഉപയോക്താവിന് അച്ചടി മാസിക ലഭിക്കുന്നുണ്ടോ എന്ന് സൂചിപ്പിക്കുന്നു.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='പ്രാഥമിക ബന്ധപ്പെടൽ മാർഗ്ഗം വിജയകരമായി പരിശോധിച്ചതിന്റെ അടിസ്ഥാനത്തിലുള്ള അക്കൗണ്ട് നില.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='സുരക്ഷാ ഓഡിറ്റിനും അനധികൃത അക്കൗണ്ട് പ്രവേശനം കണ്ടെത്താനും നിരീക്ഷിക്കുന്നു.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, help_text='അനിവാര്യമല്ലാത്ത മാർക്കറ്റിംഗ് അറിയിപ്പുകൾ സ്വീകരിക്കാനുള്ള ഉപയോക്താവിന്റെ തിരഞ്ഞെടുപ്പ്.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='newsletter_opt_in_at',
            field=models.DateTimeField(blank=True, help_text='വാർത്താക്കുറിപ്പ് സമ്മത നില അവസാനം മാറിയ സമയമുദ്ര.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='phone_number_encrypted',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Fernet-എൻക്രിപ്റ്റ് ചെയ്ത ഫോൺ നമ്പർ. നേരിട്ടുള്ള DB ഡമ്പുകളിൽ വായിക്കാനാവില്ല.', max_length=255, verbose_name='ഫോൺ നമ്പർ (എൻക്രിപ്റ്റഡ്)'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='phone_number_hash',
            field=models.CharField(help_text='ഫോൺ നമ്പറിന്റെ HMAC-SHA256. വേഗതയേറിയതും സുരക്ഷിതവുമായ കൃത്യ-പൊരുത്ത തിരയലുകൾക്ക് ഉപയോഗിക്കുന്നു.', max_length=64, unique=True, verbose_name='ഫോൺ നമ്പർ (ഹാഷ്)'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='pincode',
            field=models.CharField(blank=True, help_text='6-അക്ക ഇന്ത്യൻ പിൻകോഡ്.', max_length=6, validators=[django.core.validators.RegexValidator(message='സാധുവായ 6-അക്ക ഇന്ത്യൻ പിൻകോഡ് നൽകുക.', regex='^[1-9][0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='print_delivery_status',
            field=models.CharField(choices=[('active', 'സജീവ ഡെലിവറി'), ('paused', 'താൽക്കാലികമായി നിർത്തി'), ('returned', 'വിലാസ പ്രശ്നം / തിരികെ വന്നു'), ('inactive', 'അച്ചടി പതിപ്പ് ഇല്ല')], default='inactive', help_text='പ്രിന്റ് ഡെലിവറിയുടെ നിലവിലെ ലോജിസ്റ്റിക് നില.', max_length=20),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='print_expiry_date',
            field=models.DateField(blank=True, help_text='പ്രിന്റ് വരിസംഖ്യ അവസാനിക്കുന്നത് (ഡിജിറ്റൽ കാലാവധിയിൽ നിന്ന് വ്യത്യസ്തമാകാം).', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='privacy_version',
            field=models.CharField(blank=True, help_text='സമ്മതം നൽകിയ സ്വകാര്യതാ നയത്തിന്റെ പതിപ്പ് (സമ്മത പതിപ്പ് രേഖയ്ക്ക് ആവശ്യം).', max_length=20),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='നിങ്ങളുടെ അഭിപ്രായങ്ങൾക്കൊപ്പം ദൃശ്യമാകും.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='read_articles',
            field=models.ManyToManyField(blank=True, help_text='ഈ വായനക്കാരൻ വായിച്ച ലേഖനങ്ങൾ.', related_name='readers', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='read_history_consent_at',
            field=models.DateTimeField(blank=True, help_text='വായനാ ചരിത്രം ട്രാക്ക് ചെയ്യാൻ സമ്മതം നൽകിയ സമയമുദ്ര. പിൻവലിക്കുമ്പോൾ മായ്ക്കപ്പെടും.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='വ്യാജ ബോട്ട് രജിസ്ട്രേഷനുകൾ കണ്ടെത്താനും തടയാനും സൈൻഅപ്പിൽ രേഖപ്പെടുത്തുന്നു.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='staff_granted_by_board',
            field=models.BooleanField(default=False, help_text='നിലവിലെ എഡിറ്റോറിയൽ ബോർഡിൽ അംഗമായതിനാൽ is_staff സ്വയമേവ നൽകിയപ്പോൾ True (literati.sync_editorial_staff കാണുക). ബോർഡ് വിട്ടാൽ ഈ ഫ്ലാഗ് ഉള്ളവരുടെ മാത്രം അനുമതി പിൻവലിക്കും — നേരിട്ട് നിയമിച്ച സ്റ്റാഫും സൂപ്പർയൂസർമാരും ഒരിക്കലും തരംതാഴ്ത്തപ്പെടില്ല.'),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='state',
            field=models.CharField(blank=True, choices=[('', '— സംസ്ഥാനം തിരഞ്ഞെടുക്കുക —'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='subscription_end',
            field=models.DateTimeField(blank=True, help_text='നിലവിലെ വരിസംഖ്യ കാലയളവ് അവസാനിക്കുന്നത്.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='subscription_plan',
            field=models.CharField(choices=[('none', 'വരിസംഖ്യ ഇല്ല'), ('complimentary', 'സൗജന്യം (താൽക്കാലിക പ്രവേശനം)'), ('1_month', '1 മാസം'), ('3_months', '3 മാസം'), ('6_months', '6 മാസം'), ('1_year', '1 വർഷം'), ('3_years', '3 വർഷം'), ('5_years', '5 വർഷം')], default='none', help_text='സജീവ വരിസംഖ്യ പ്ലാൻ.', max_length=20),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='subscription_start',
            field=models.DateTimeField(blank=True, help_text='നിലവിലെ വരിസംഖ്യ കാലയളവ് ആരംഭിച്ചത്.', null=True),
        ),
        migrations.AlterField(
            model_name='readeruser',
            name='terms_version',
            field=models.CharField(blank=True, help_text='ഉപയോക്താവ് അംഗീകരിച്ച സേവന വ്യവസ്ഥകളുടെ പതിപ്പ്.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ഇത് നിലവിലെ സജീവ വരിസംഖ്യ രേഖയാണോ എന്ന ഫ്ലാഗ്.'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='ഈ വരിസംഖ്യ കാലാവധിക്കു മുൻപ് റദ്ദാക്കിയോ എന്ന ഫ്ലാഗ്.'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='payment_details',
            field=models.ForeignKey(blank=True, help_text='ഈ വരിസംഖ്യയുമായി ബന്ധപ്പെട്ട പേയ്\u200cമെന്റ് ഇടപാട് വിവരങ്ങൾ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_records', to='reader.paymentdetails'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='reader',
            field=models.ForeignKey(blank=True, help_text='ഈ വരിസംഖ്യ രേഖയുമായി ബന്ധപ്പെട്ട വായനക്കാരൻ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription_end',
            field=models.DateTimeField(help_text='ഈ വരിസംഖ്യ കാലയളവ് അവസാനിക്കുന്നത്/അവസാനിച്ചത്.'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription_plan',
            field=models.CharField(choices=[('none', 'വരിസംഖ്യ ഇല്ല'), ('complimentary', 'സൗജന്യം (താൽക്കാലിക പ്രവേശനം)'), ('1_month', '1 മാസം'), ('3_months', '3 മാസം'), ('6_months', '6 മാസം'), ('1_year', '1 വർഷം'), ('3_years', '3 വർഷം'), ('5_years', '5 വർഷം')], help_text='വരിസംഖ്യ പ്ലാൻ തരം.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription_start',
            field=models.DateTimeField(help_text='ഈ വരിസംഖ്യ കാലയളവ് ആരംഭിച്ചത്.'),
        ),
    ]
