# Generated by Django 5.2.14 on 2026-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0002_postboxbacknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbox',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postbox_images/', verbose_name='Attached Image'),
        ),
    ]
