# Generated by Django 5.2.14 on 2026-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0003_postbox_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbox',
            name='feedback_type',
            field=models.CharField(choices=[('bug', 'ബഗ് റിപ്പോർട്ട്'), ('suggestion', 'നിർദ്ദേശം'), ('content', 'ഉള്ളടക്കത്തിലെ പ്രശ്നം'), ('general', 'പൊതുവായ ഫീഡ്\u200cബാക്ക്')], default='general', max_length=20, verbose_name='Type'),
        ),
    ]
