# Generated by Django 5.2.11 on 2026-04-25 12:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(blank=True, default='© 2024 My Wagtail Site. All rights reserved.', help_text='Copyright line shown at the bottom of the footer.', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Optional short tagline shown above the links.', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Optional rich-text content (address, social links, etc.).')),
            ],
            options={
                'verbose_name': 'Site Footer',
                'verbose_name_plural': 'Site Footers',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.sitefooter')),
            ],
        ),
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_alt_text', models.CharField(blank=True, default='Site logo', help_text='Alt text for the logo image (for accessibility).', max_length=100)),
                ('organization_title', models.CharField(blank=True, help_text='Organization name displayed to the right of the logo.', max_length=100)),
                ('site_title', models.CharField(default='My Wagtail Site', help_text='Title displayed in the centre of the header.', max_length=100)),
                ('site_title_url', models.CharField(blank=True, default='/', help_text='URL the site title links to (defaults to home page).', max_length=255)),
                ('logo', models.ForeignKey(blank=True, help_text='Logo displayed on the left side of the header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site_title_image', models.ForeignKey(blank=True, help_text='Image displayed in the centre of the header (replaces site_title text if set).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Header',
                'verbose_name_plural': 'Site Headers',
            },
        ),
    ]
