# Generated by Django 5.2.11 on 2026-02-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_alt_text', models.CharField(blank=True, default='Site logo', help_text='Alt text for the logo image (for accessibility).', max_length=100)),
                ('site_title', models.CharField(default='My Wagtail Site', help_text='Title displayed in the centre of the header.', max_length=100)),
                ('site_title_url', models.CharField(blank=True, default='/', help_text='URL the site title links to (defaults to home page).', max_length=255)),
                ('logo', models.ForeignKey(blank=True, help_text='Logo displayed on the left side of the header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Header',
                'verbose_name_plural': 'Site Headers',
            },
        ),
    ]
