# Generated by Django 5.2.14 on 2026-05-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customlogentry'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['column', 'sort_order', 'label']},
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='body',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='tagline',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='column',
            field=models.CharField(choices=[('col1', 'Column 1'), ('col2', 'Column 2'), ('col3', 'Column 3')], default='col1', help_text='Which column this link appears in.', max_length=10),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first within the column.'),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='about_text',
            field=models.TextField(blank=True, help_text='Descriptive paragraph shown below the link columns (e.g. ownership/editorial independence statement).'),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='col1_header',
            field=models.CharField(blank=True, default='Explore', help_text='Heading for the first link column.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='col2_header',
            field=models.CharField(blank=True, default='Company', help_text='Heading for the second link column.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='col3_header',
            field=models.CharField(blank=True, default='More', help_text='Heading for the third link column.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full URL including https://'),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='footer_logo',
            field=models.ForeignKey(blank=True, help_text='Logo shown in the bottom-left of the footer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='logo_alt_text',
            field=models.CharField(blank=True, default='Site logo', max_length=100),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='reddit_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='X / Twitter URL'),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
