# Generated by Django 5.2.14 on 2026-05-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_footerlink_options_remove_sitefooter_body_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Pick an internal page. Takes priority over the URL field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='column',
            field=models.CharField(choices=[('col1', 'Column 1'), ('col2', 'Column 2'), ('col3', 'Column 3')], default='col1', max_length=10),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, help_text='Used only when no page is chosen above.', max_length=255),
        ),
    ]
