# Generated by Django 5.2.11 on 2026-03-01 02:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_siteheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, help_text='Tagline displayed in the footer.', max_length=255)),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text shown at the bottom of the footer.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Footer',
                'verbose_name_plural': 'Site Footers',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_url', models.CharField(max_length=255)),
                ('link_text', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='home.sitefooter')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
