# Generated by Django 5.2.14 on 2026-05-29 19:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footerlink_page_alter_footerlink_column_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, help_text='Internal label (never shown on the site). Useful when this section has multiple columns.', max_length=50)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='col1_header',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='col2_header',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='col3_header',
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='about_text',
            field=models.TextField(blank=True, help_text='Descriptive paragraph shown below the link sections (e.g. editorial independence statement).'),
        ),
        migrations.CreateModel(
            name='FooterColumnLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='External URL — used only when no internal page is chosen above.', max_length=255)),
                ('column', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_links', to='home.footercolumn')),
                ('page', models.ForeignKey(blank=True, help_text='Pick an internal page. Takes priority over the URL field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(blank=True, help_text="Section heading shown above the link column(s) — e.g. 'Explore', 'Company'.", max_length=100)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.sitefooter')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='home.footersection'),
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
