# Generated by Django 5.2.11 on 2026-03-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitefooter_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_1_label',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_1_url',
            field=models.CharField(blank=True, default='/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_2_label',
            field=models.CharField(blank=True, default='Search', max_length=50),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_2_url',
            field=models.CharField(blank=True, default='/search/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_3_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_3_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_4_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='nav_link_4_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='site_name',
            field=models.CharField(default='Icarus', help_text='Site name displayed in the footer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='copyright_text',
            field=models.CharField(blank=True, default='All rights reserved.', help_text='Copyright text (year is added automatically).', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='tagline',
            field=models.CharField(blank=True, default='Exploring the frontiers of knowledge.', help_text='Short tagline displayed beneath the site name.', max_length=255),
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
