# Generated by Django 5.2.14 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_footercolumn_remove_sitefooter_col1_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercolumnlink',
            name='dynamic_url_key',
            field=models.CharField(blank=True, choices=[('', '— Fixed page or URL (default) —'), ('current_issue_url', 'Current Issue — updates when a new issue is published'), ('latest_issue_url', 'Issue Index: Latest'), ('most_read_issue_url', 'Issue Index: Most Read'), ('latest_article_url', 'Article Index: Latest'), ('most_read_article_url', 'Article Index: Most Read')], default='', help_text='Choose a destination that updates automatically. If set, the Page and URL fields below are ignored.', max_length=30),
        ),
    ]
