# Generated by Django 5.2.11 on 2026-03-01 03:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sitefooter_nav_link_1_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_1_label',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_1_url',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_2_label',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_2_url',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_3_label',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_3_url',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_4_label',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='nav_link_4_url',
        ),
        migrations.RemoveField(
            model_name='sitefooter',
            name='site_name',
        ),
        migrations.AddField(
            model_name='sitefooter',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional rich-text content (address, social links, etc.).'),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2024 My Wagtail Site. All rights reserved.', help_text='Copyright line shown at the bottom of the footer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='tagline',
            field=models.CharField(blank=True, help_text='Optional short tagline shown above the links.', max_length=255),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.sitefooter')),
            ],
        ),
    ]
