# Generated by Django 5.2.11 on 2026-03-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_sitefooter_nav_link_1_label_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheader',
            name='organization_title',
            field=models.CharField(blank=True, help_text='Organization name displayed to the right of the logo.', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheader',
            name='site_title_image',
            field=models.ForeignKey(blank=True, help_text='Image displayed in the centre of the header (replaces site_title text if set).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
