# Generated by Django 5.2.14 on 2026-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_footercolumnlink_dynamic_url_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Contact Settings',
            },
        ),
    ]
