# Generated by Django 5.2.14 on 2026-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sitecontactsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercolumnlink',
            name='dynamic_url_key',
            field=models.CharField(blank=True, choices=[('', '— Fixed page or URL (default) —'), ('current_issue_url', 'Current Issue — updates when a new issue is published'), ('previous_issue_url', 'Previous Issue'), ('latest_issue_url', 'Issue Index: Latest'), ('most_read_issue_url', 'Issue Index: Most Read'), ('latest_article_url', 'Article Index: Latest'), ('most_read_article_url', 'Article Index: Most Read'), ('most_read_topics_url', 'Most Read Topics — rolling 30-day most read'), ('most_read_authors_url', 'Most Read Authors — rolling 30-day most read'), ('archive_list_url', 'Archive')], default='', help_text='Choose a destination that updates automatically. If set, the Page and URL fields below are ignored.', max_length=30),
        ),
    ]
