# Generated by Django 5.2.11 on 2026-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literati',
            name='role',
            field=models.CharField(blank=True, verbose_name='Title / Role of the author'),
        ),
    ]
