# Generated by Django 5.2.11 on 2026-03-07 15:20

import modelcluster.fields
import phonenumber_field.modelfields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_topic_color'),
        ('literati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literati',
            name='areas_of_interest',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='issue.topic'),
        ),
        migrations.AddField(
            model_name='literati',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='literati',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='literati',
            name='social_media_links',
            field=wagtail.fields.StreamField([('social_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('website', 'Website')]}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1)]], {})}),
        ),
    ]
