# Generated by Django 5.2.11 on 2026-03-07 17:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0002_literati_areas_of_interest_literati_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literati',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Bio'),
        ),
    ]
