# Generated by Django 5.2.14 on 2026-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0003_literati_address_line_1_literati_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literati',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Tick to display this email address on the public author profile page.', verbose_name='Show email publicly'),
        ),
        migrations.AddField(
            model_name='literati',
            name='show_phone_number',
            field=models.BooleanField(default=False, help_text='Tick to display this phone number on the public author profile page.', verbose_name='Show phone number publicly'),
        ),
    ]
