# Generated by Django 5.2.11 on 2026-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0003_alter_literati_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='literati',
            name='read_fully_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
