# Generated by Django 5.2.14 on 2026-06-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0004_add_contact_visibility_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboardmember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this member is currently active on the board.'),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='joined_at',
            field=models.DateField(blank=True, help_text='Date when this member joined the editorial board.', null=True),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='left_at',
            field=models.DateField(blank=True, help_text='Date when this member left the editorial board.', null=True),
        ),
        migrations.CreateModel(
            name='EditorialBoardMembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('associate', 'Associate Editor'), ('managing', 'Managing Editor'), ('board', 'Board Member')], max_length=50)),
                ('joined_at', models.DateField(help_text='Date when this membership period began.')),
                ('left_at', models.DateField(blank=True, help_text='Date when this membership period ended. Null if still active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='literati.editorialboard')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_membership_history', to='literati.literati')),
            ],
            options={
                'verbose_name': 'Board Membership History',
                'verbose_name_plural': 'Board Membership History',
                'ordering': ['-joined_at'],
            },
        ),
    ]
