# Generated by Django 5.2.11 on 2026-04-18 00:01

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0005_authorindexpagetag_authorindexpage_tags_literatitag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Editorial Boards',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('associate', 'Associate Editor'), ('managing', 'Managing Editor'), ('board', 'Board Member')], default='editor', max_length=50)),
                ('board', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='literati.editorialboard')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='literati.literati')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
