# Generated by Django 5.2.14 on 2026-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literati', '0005_editorialboardmember_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboard',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Marks this as the sitting editorial board. Saving a board with this ticked automatically unticks every other board — exactly one board is current at a time. Old boards are never deleted; they remain attached to their issues for history.'),
        ),
    ]
