# Generated by Django 5.2.11 on 2026-04-25 12:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('literati', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('file_path', models.CharField(help_text='Relative path from ARCHIVE_DIR', max_length=1000)),
                ('total_pages', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archive Document',
                'verbose_name_plural': 'Archive Documents',
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, help_text='Source page number in the PDF (1-indexed)', null=True)),
                ('chunk_text', models.TextField()),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('chunk_text', config='simple'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, help_text='pgvector embedding of the chunk text')),
                ('language', models.CharField(default='ml', help_text='ISO language code of the chunk text', max_length=10)),
                ('chunk_index', models.IntegerField(default=0, help_text='Order of this chunk within the document/article/author')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='articles.article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='literati.literati')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='the_librarian.archivedocument')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='the_librari_documen_3d7f12_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='the_librari_search__3de60d_gin')],
            },
        ),
    ]
