# Generated by Django 5.2.11 on 2026-03-19 15:54

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_librarian', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('file_path', models.CharField(help_text='Relative path from ARCHIVE_DIR', max_length=1000)),
                ('total_pages', models.IntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archive Document',
                'verbose_name_plural': 'Archive Documents',
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Source page number in the PDF (1-indexed)')),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='pgvector embedding of the chunk text')),
                ('chunk_index', models.IntegerField(default=0, help_text='Order of this chunk within the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='the_librarian.archivedocument')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='the_librari_documen_3d7f12_idx')],
            },
        ),
    ]
