# Generated by Django 5.2.14 on 2026-06-10 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Display title, e.g. 'ശാസ്ത്രഗതി January 2026'", max_length=500)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True)),
                ('volume', models.IntegerField(db_index=True, help_text='Volume number')),
                ('issue_number', models.IntegerField(help_text='Issue number within the volume', verbose_name='Issue No.')),
                ('description', models.TextField(blank=True, help_text='Optional editorial note or summary shown on the archive page')),
                ('pdf_file', models.FileField(help_text='Upload the PDF.  Stored at MEDIA_ROOT/archive/.', upload_to='archive/')),
                ('thumbnail', models.ImageField(blank=True, help_text="Cover thumbnail shown in the archive grid.  Auto-generated from the PDF's first page if left blank (requires PyMuPDF: pip install pymupdf).", null=True, upload_to='archive/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_document', models.OneToOneField(blank=True, help_text='Link to the ingested ArchiveDocument for full-text search.  Set automatically if you ingest the PDF after uploading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazine_issue', to='the_librarian.archivedocument')),
            ],
            options={
                'verbose_name': 'Magazine Issue',
                'verbose_name_plural': 'Magazine Issues',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
