# Generated by Django 5.2.14 on 2026-06-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_librarian', '0002_archiveissue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveissue',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Archive Issue', 'verbose_name_plural': 'Archive Issues'},
        ),
        migrations.AlterField(
            model_name='archiveissue',
            name='archive_document',
            field=models.OneToOneField(blank=True, help_text='Link to the ingested ArchiveDocument for full-text search.  Set automatically if you ingest the PDF after uploading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Archive_Issue', to='the_librarian.archivedocument'),
        ),
    ]
