# Generated by Django 5.2.14 on 2026-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_librarian', '0003_alter_archiveissue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveissue',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated if nothing is uploaded', null=True, upload_to='archive/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='archiveissue',
            name='title',
            field=models.CharField(help_text="Display title, e.g. 'ജനുവരി 2026'", max_length=500),
        ),
    ]
