# Generated by Django 5.2.11 on 2026-03-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_opened_count'),
        ('literati', '0004_literati_read_fully_count'),
        ('the_librarian', '0003_hnsw_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='articles.article'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='literati.literati'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='language',
            field=models.CharField(default='ml', help_text='ISO language code of the chunk text', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(default=0, help_text='Order of this chunk within the document/article/author'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='the_librarian.archivedocument'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Source page number in the PDF (1-indexed)', null=True),
        ),
    ]
