# Generated by Django 5.2.11 on 2026-04-01 01:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_opened_count'),
        ('literati', '0004_literati_read_fully_count'),
        ('the_librarian', '0004_documentchunk_article_documentchunk_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('chunk_text', config='simple'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='the_librari_search__3de60d_gin'),
        ),
    ]
