# Generated by Django 5.2.11 on 2026-04-02 12:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_librarian', '0005_documentchunk_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, help_text='pgvector embedding of the chunk text'),
        ),
    ]
