# Generated by Django 5.2.14 on 2026-06-24 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_librarian', '0005_documentchunk_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='file_path',
            field=models.CharField(help_text='Relative path from ARCHIVE_DIR (or MEDIA_ROOT for ArchiveIssue uploads)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='archiveissue',
            name='archive_document',
            field=models.OneToOneField(blank=True, help_text='Link to the ingested ArchiveDocument for full-text search.  Set automatically when ingestion completes after uploading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Archive_Issue', to='the_librarian.archivedocument'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(default=0, help_text='Order of this chunk within the document/article/author/issue'),
        ),
    ]
