# Generated by Django 5.2.14 on 2026-06-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alter_issue_editorial'),
        ('the_librarian', '0006_alter_archivedocument_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='issue.topic'),
        ),
    ]
