# Generated by Django 5.2.14 on 2026-07-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_librarian', '0011_remote_worker_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(default=0, help_text='Order of this chunk within the document/author/issue'),
        ),
    ]
