"""
Django settings for Icarus project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
ACCOUNT_LOGIN_METHODS = {"phone"}
ACCOUNT_SIGNUP_FIELDS = [
  'phone*',
  'name*',
  'password1*',
  'password2*',
]
# ACCOUNT_USER_MODEL_PHONE_FIELD = 'phone_number'
ACCOUNT_USER_MODEL_PHONE_FIELD = 'phone_number_encrypted'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_PHONE_VERIFICATION = "none"  # No SMS backend; skip phone verification
# ACCOUNT_SIGNUP_FORM_CLASS = 'reader.forms.AllauthSignupForm'
ACCOUNT_SIGNUP_FORM_CLASS = 'reader.auth_forms.CustomSignupForm'
ACCOUNT_FORMS = {
    'login': 'reader.auth_forms.CustomLoginForm',
    # 'signup': 'reader.auth_forms.CustomSignupForm',
}
ACCOUNT_LOGIN_ON_SIGNUP = True
ACCOUNT_ADAPTER = 'reader.adapter.CustomAccountAdapter'
AUTH_USER_MODEL = 'reader.ReaderUser'
ACCOUNT_SIGNUP_REDIRECT_URL = '/reader/profile/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUDITLOG_LOGENTRY_MODEL = 'home.CustomLogEntry'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path
from environs import Env

env = Env()
env.read_env() 

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

from datetime import timedelta

AXES_FAILURE_LIMIT = env.int('AXES_FAILURE_LIMIT', default=5)                      # Lock out after 5 failures
AXES_COOLOFF_TIME = env.int('AXES_COOLOFF_TIME', default=timedelta(hours=1))      # Duration of lockout

# ── Cryptographic Field Encryption Settings ───────────────────────────
# Required by django-fernet-encrypted-fields for field-level encryption.
# In your production environment file (.env), declare a cryptographically secure string.
SALT_KEY = env.str('SALT_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'kadannal-koodu.miku-brill.ts.net',  
]

CSRF_TRUSTED_ORIGINS = [
    'https://kadannal-koodu.miku-brill.ts.net',
]

# Application definition

INSTALLED_APPS = [
    "auditlog",
    "channels",
    "channels_postgres",
    "django_q",
    "home",
    "search",
    "articles",
    "literati",
    "issue",
    "reader",
    "axes",
    "kalapila",
    "hitcount",
    "the_librarian",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.table_block",
    "wagtail.embeds",
    "wagtail.sites",
    # "wagtail.users",
    "reader.apps.CustomWagtailUsersAppConfig",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.contrib.sitemaps",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.humanize",
    "allauth",
    "allauth.account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "kalapila.middleware.UserNotificationMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "Icarus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Icarus.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:////{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# channels_postgres requires a database connection named 'channels_postgres'
DATABASES['channels_postgres'] = DATABASES['default']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'reader.backends.PhoneNumberBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "ശാസ്ത്രഗതി"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip', 'mp3', 'wav', 'm4a', 'aac', 'flac', 'ogg', 'opus', 'mp4', 'webm', 'ogv']

# ── Reader / Paywall ──────────────────────────────────────────────────
FREE_ARTICLE_LIMIT = env.int("FREE_ARTICLE_LIMIT", 3)  # Number of free articles for non-subscribed readers
LOGIN_REDIRECT_URL = env.str("LOGIN_REDIRECT_URL", '/')
LOGIN_URL = env.str("LOGIN_URL", '/accounts/login/')
# ACCOUNT_LOGIN_REDIRECT_URL = env.str("LOGIN_REDIRECT_URL", '/')

# ── The Librarian ─────────────────────────────────────────────────────
ARCHIVE_DIR = env.path("ARCHIVE_DIR", BASE_DIR / "archive")
LIBRARIAN_EMBEDDER_TYPE = env.str("EMBEDDER_TYPE", "HuggingFace")
LIBRARIAN_EMBEDDING_MODEL = env.str("EMBEDDING_MODEL_NAME", "all-mpnet-base-v2")
LIBRARIAN_COLLECTION_NAME = env.str("COLLECTION_NAME", "sg-archive")
LIBRARIAN_EMBEDDING_DIM = env.int("EMBEDDING_DIM", 768)
LIBRARIAN_EMBED_BATCH_SIZE = env.int("EMBED_BATCH_SIZE", 64)

# ── Email & Password Reset ───────────────────────────────────────────
# Default to console backend for local testing, can be toggled via .env
EMAIL_BACKEND = env.str(
    "EMAIL_BACKEND", 
    default="django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = env.str("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="ശാസ്ത്രഗതി <noreply@example.com>")

# Enable framing from SAMEORIGIN to allow PDF rendering within search interface
X_FRAME_OPTIONS = "SAMEORIGIN"
WAGTAILEMBEDS_RESPONSIVE_HTML = True


TAGGIT_CASE_INSENSITIVE = True

DAYS_BEFORE_PURGE = env.int("DAYS_BEFORE_PURGE", default=30)

# Q2 cluster configuration
# 'name' can be 'default', 'redis', or 'dq' (for database)
# Adjust 'workers', 'timeout', and 'queue_limit' based on your server resources
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'timeout': 8400,
    'retry': 8410,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default'
}

#Channel layer settings
CHANNEL_LAYER_CONFIG = dj_database_url.config(
    default=f"sqlite:////{BASE_DIR / 'db.sqlite3'}"
)
CHANNEL_LAYER_CONFIG.setdefault('TIME_ZONE', TIME_ZONE)
CHANNEL_LAYER_CONFIG.setdefault('OPTIONS', {})
CHANNEL_LAYER_CONFIG.setdefault('AUTOCOMMIT', True)

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_postgres.core.PostgresChannelLayer',
        'CONFIG': CHANNEL_LAYER_CONFIG,
    }
}

ASGI_APPLICATION = "Icarus.asgi.application"

# GOOGLE_TTS_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'secrets', 'google_credentials.json')
GOOGLE_CREDENTIALS_JSON = env.str("GOOGLE_CREDENTIALS_JSON", "")